### ISSUE TITLE
New functions of psutil

### ISSUE THREAD

**Issue by mcmindcoder** [GrbavaCigla/psutil-cpp#1]
Hey Alexa,
I'm cpp software engineer and I work at cyngn.com. Right now I'm implementing cpp version of psutil lib. Similar to what you have done here. I'd like to join our efforts and make my code available for open source community. But I have some licensing issues which preventing me from proper contributing. Would you be available to have a quick chat about that and discuss the ways we can collaborate.I could not find you on linkedin. My linkedin account: https://www.linkedin.com/in/mchabanov/

**Comment by GrbavaCigla** [comment]
Yeah, sure, I will send you an email :D

**Comment by GrbavaCigla** [comment]
I started restructuring and fixing the project (#2). I am still waiting for your email :D

**Comment by mcmindcoder** [comment]
Alexa, I can not send you email. Because I don't know your email address. When you posting messages here I only can see github proxy mailbox - notifications@github.com
That is why I left my email here and asked you to message me directly

**Comment by GrbavaCigla** [comment]
Yeah, I sent this message because I thought you didn't recieve my mail...

Edit: Are you sure you sent me the correct mail address?

Edit2: Can I send an email to address listed in your github profile page?

**Comment by mcmindcoder** [comment]
Found it in Spam folder. I'll respond
