### ISSUE TITLE
Im sory, but i have installed it under  Ubuntu 22.04.  How to include  in  cpp ???

### ISSUE THREAD

**Issue by casic** [GrbavaCigla/psutil-cpp#5]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GrbavaCigla** [comment]
Look at the demo file: https://github.com/GrbavaCigla/psutil-cpp/blob/master/demo/linux.cpp
